import { Link } from "@tanstack/react-router";
import { Menu, Search, ShoppingBag, UserRound, X } from "lucide-react";
import { useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { products } from "@/lib/catalog";
import { BrandLogo } from "./brand-logo";
import { useStore } from "./store-context";
const nav=[[/,"Início"],["/colecao","Coleção"],["/biquinis","Biquínis"],["/maios","Maiôs"],["/saidas","Saídas"],["/acessorios","Acessórios"]] as const;
export function SiteShell({children}:{children:ReactNode}){const [menu,setMenu]=useState(false);const [search,setSearch]=useState(false);const [query,setQuery]=useState("");const {count}=useStore();const found=products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase()));return <div className="min-h-screen bg-background"><div className="bg-primary px-4 py-2 text-center text-xs uppercase tracking-[.18em] text-primary-foreground">Frete grátis acima de R$ 499 · Troca fácil em 30 dias</div><header className="sticky top-0 z-40 border-b border-border/70 bg-background/95 backdrop-blur"><div className="mx-auto grid h-20 max-w-7xl grid-cols-[1fr_auto_1fr] items-center px-5"><Button variant="ghost" size="icon" className="md:hidden" onClick={()=>setMenu(!menu)} aria-label="Abrir menu">{menu?<X/>:<Menu/>}</Button><nav className="hidden items-center gap-6 md:flex">{nav.slice(0,3).map(([to,label])=><Link key={to} to={to} className="nav-link">{label}</Link>)}</nav><Link to="/" className="justify-self-center"><BrandLogo/></Link><div className="flex justify-self-end gap-1"><Button variant="ghost" size="icon" onClick={()=>setSearch(!search)} aria-label="Buscar"><Search/></Button><Button variant="ghost" size="icon" className="hidden sm:inline-flex" aria-label="Conta"><UserRound/></Button><Button variant="ghost" size="icon" asChild><Link to="/sacola" aria-label={`Sacola com ${count} itens`} className="relative"><ShoppingBag/><span className="absolute right-0 top-0 flex h-4 min-w-4 items-center justify-center rounded-full bg-primary px-1 text-[9px] text-primary-foreground">{count}</span></Link></Button></div></div><nav className="mx-auto hidden max-w-7xl justify-center gap-8 border-t border-border/50 py-3 md:flex">{nav.slice(3).map(([to,label])=><Link key={to} to={to} className="nav-link">{label}</Link>)}<Link to="/historia" className="nav-link">Nossa história</Link></nav>{menu&&<nav className="border-t border-border bg-card px-5 py-6 md:hidden">{[...nav,["/historia","Nossa história"] as const].map(([to,label])=><Link key={to} to={to} onClick={()=>setMenu(false)} className="block border-b border-border py-3 font-serif text-xl">{label}</Link>)}</nav>}{search&&<div className="border-t border-border bg-card px-5 py-5"><div className="mx-auto max-w-xl"><Input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busque por biquíni, maiô, saída..." aria-label="Buscar produtos"/>{query&&<div className="mt-3 grid gap-2">{found.length?found.slice(0,4).map(p=><Link key={p.id} to="/produto/$slug" params={{slug:p.slug}} onClick={()=>setSearch(false)} className="flex items-center justify-between border-b border-border py-2 text-sm"><span>{p.name}</span><span className="text-muted-foreground">{p.category}</span></Link>):<p className="py-3 text-sm text-muted-foreground">Nenhum produto encontrado.</p>}</div>}</div></div>}</header>{children}<Footer/></div>}
function Footer(){return <footer className="border-t border-border bg-card"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 md:grid-cols-4"><div><BrandLogo/><p className="mt-4 max-w-xs text-sm leading-6 text-muted-foreground">Moda praia feita para viver o sol, sentir o mar e escolher a liberdade.</p></div><div><h3 className="footer-title">Navegue</h3><Link to="/colecao">Coleção</Link><Link to="/historia">Nossa história</Link></div><div><h3 className="footer-title">Atendimento</h3><a href="mailto:oi@agualimpa.com.br">Fale conosco</a><span>Trocas e devoluções</span></div><div><h3 className="footer-title">Siga a maré</h3><span>Instagram</span><span>Pinterest</span></div></div><div className="border-t border-border px-5 py-5 text-center text-xs text-muted-foreground">© 2026 ÁGUA LIMPA BEACHWEAR · SOL • MAR • LIBERDADE</div></footer>}
