import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { useState } from "react";
import { Minus, Plus, ShieldCheck, Truck, RefreshCcw } from "lucide-react";
import { products, money } from "@/lib/catalog";
import { Button } from "@/components/ui/button";
import { ProductCard } from "@/components/store/product-card";
import { useStore } from "@/components/store/store-context";
export const Route=createFileRoute("/produto/$slug")({loader:({params})=>{const product=products.find(p=>p.slug===params.slug);if(!product)throw notFound();return product},head:({loaderData:p})=>({meta:[{title:p?`${p.name} — Água Limpa Beachwear`:"Produto indisponível"},{name:"description",content:p?.description??"Produto indisponível."},{property:"og:title",content:p?.name??"Produto"},{property:"og:description",content:p?.description??"Produto indisponível."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:ProductPage});
function ProductPage(){const p=Route.useLoaderData();const [size,setSize]=useState(p.sizes[0]??"");const [qty,setQty]=useState(1);const [added,setAdded]=useState(false);const {add}=useStore();return <main className="section-shell py-8 md:py-14"><div className="mb-6 text-xs text-muted-foreground"><Link to="/colecao">Coleção</Link> / {p.name}</div><div className="grid gap-10 md:grid-cols-2 lg:gap-16"><div className="grid gap-3 sm:grid-cols-2"><img src={p.image} alt={p.name} width={960} height={1200} className="aspect-[4/5] w-full object-cover sm:col-span-2"/><img src={p.image} alt={`Detalhe de ${p.name}`} width={960} height={1200} loading="lazy" className="aspect-square w-full object-cover object-top"/><img src={p.image} alt={`Textura de ${p.name}`} width={960} height={1200} loading="lazy" className="aspect-square w-full object-cover object-bottom"/></div><div className="md:sticky md:top-36 md:h-fit"><p className="eyebrow">{p.category}</p><h1 className="mt-2 text-5xl">{p.name}</h1><p className="mt-5 text-2xl">{money(p.price)}</p><p className="mt-1 text-sm text-muted-foreground">ou 6x de {money(p.price/6)} sem juros</p><p className="mt-7 leading-7 text-muted-foreground">{p.description}</p><div className="mt-8"><div className="mb-3 flex justify-between text-sm"><span>Tamanho</span><span className="text-muted-foreground">Guia de medidas</span></div><div className="flex gap-2">{p.sizes.map(s=><Button key={s} variant={size===s?"default":"outline"} size="icon" onClick={()=>setSize(s)}>{s}</Button>)}</div></div><div className="mt-6"><p className="mb-3 text-sm">Cor · {p.color}</p><span className="block h-7 w-7 rounded-full bg-primary ring-2 ring-primary ring-offset-2 ring-offset-background"/></div><div className="mt-8 flex gap-3"><div className="flex h-10 items-center border border-border"><Button variant="ghost" size="icon" onClick={()=>setQty(Math.max(1,qty-1))}><Minus/></Button><span className="w-8 text-center">{qty}</span><Button variant="ghost" size="icon" onClick={()=>setQty(qty+1)}><Plus/></Button></div><Button className="flex-1" onClick={()=>{add(p,size,qty);setAdded(true)}}>{added?"Adicionado à sacola":"Adicionar à sacola"}</Button></div><div className="mt-8 divide-y divide-border border-y border-border text-sm"><p className="flex gap-3 py-4"><Truck className="text-primary"/> Frete grátis acima de R$ 499</p><p className="flex gap-3 py-4"><RefreshCcw className="text-primary"/> Troca fácil em até 30 dias</p><p className="flex gap-3 py-4"><ShieldCheck className="text-primary"/> Compra segura e protegida</p></div></div></div><section className="py-20"><h2 className="mb-8 text-4xl">Você também pode gostar</h2><div className="grid grid-cols-2 gap-4 md:grid-cols-4">{products.filter(x=>x.id!==p.id).slice(0,4).map(x=><ProductCard key={x.id} product={x}/>)}</div></section></main>}
